name: cavalier # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: cavalier
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
#compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
lint:
  ignore:
    - library:
      - usr/lib/*
      - usr/bin/*

parts:
  cava:
    #after: [ fftw3f ]
    source: https://github.com/karlstav/cava.git
    source-tag: '0.8.3'
    source-depth: 1
    build-environment:
      - CFLAGS: -I/snap/gnome-42-2204-sdk/current/usr/include
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
    build-packages:
      - libfftw3-dev
    prime:
      - -usr/share
  #fftw3f:
    #source: https://www.fftw.org/fftw-3.3.10.tar.gz
    #plugin: autotools
    #autotools-configure-parameters:
    #  - --prefix=/usr
    #  - --enable-threads
    #  - --enable-shared
    #  - --disable-static
    #  - --enable-float
    #  - --enable-sse2
    #  - --enable-avx
    #  - --enable-avx-128-fma
    #build-packages:
      #- libgfortran-12-dev
  cavalier:
    after: [ cava ]
    # See 'snapcraft plugins'
    plugin: nil
    source: https://github.com/NickvisionApps/Cavalier.git
    #source-tag: ''
    source-depth: 1
    build-environment:
      - LDFLAGS: -L$CRAFT_STAGE/usr/lib
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/pkgconfig:$PKG_CONFIG_PATH
      - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    build-packages:
      - brotli
      - blueprint-compiler
      - wget
      - libiniparser-dev
    override-pull: |
      craftctl default
      wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
      chmod +x ./dotnet-install.sh
      ./dotnet-install.sh --channel 7.0
      patch -p1 < $CRAFT_PROJECT_DIR/snap/cavalier.patch
    override-build: |
      set -eux
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools
      cd $CRAFT_PART_SRC
      dotnet tool restore
      dotnet cake --target=Publish --prefix=/snap/cavalier/current/usr --ui=gnome --self-contained
      dotnet cake --target=Install --destdir=$CRAFT_PART_INSTALL
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/cavalier/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    parse-info: [ usr/share/metainfo/org.nickvision.cavalier.metainfo.xml ]
    organize:
      snap/cavalier/current: .
    prime:
      - -snap/cavalier

  deps:
    after: [ cavalier ]
    plugin: nil
    stage-packages:
      - libfftw3-double3
      - libiniparser1
    prime:
      - usr/lib/x86_64-linux-gnu/libiniparser.so.1
      - usr/lib/$CRAFT_ARCH_TRIPLET/libfftw3.so.3
      - usr/lib/$CRAFT_ARCH_TRIPLET/libfftw3.so.3.5.8
slots:
  cavalier:
    interface: dbus
    bus: session
    name: org.nickvision.cavalier
apps:
  cavalier:
    command: usr/bin/org.nickvision.cavalier
    common-id: org.nickvision.cavalier
    desktop: usr/share/applications/org.nickvision.cavalier.desktop
    extensions: [ gnome ]
    plugs:
      - audio-playback
